name: MirrorBot Environment

on:
  push:
  workflow_dispatch:
   
env:
  GitHubMail: ${{ secrets.GHMAIL }}
  GitHubName: ${{ secrets.GHUSER }}

jobs:
  debug:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Config
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Setup & Clone
        run: |
          sudo apt-get -qq -y install --no-install-recommends locales python3 python3-lxml python3-pip python3-dev libc-ares-dev libcrypto++-dev libcurl4-openssl-dev libmagic-dev libsodium-dev libsqlite3-dev libssl-dev aria2 curl ffmpeg jq p7zip-full p7zip-rar pv gcc libpq-dev unzip
          sudo apt-get -qq -y autoremove --purge ; sudo apt-get -qq -y clean
          git clone https://${{ secrets.GH_TOKEN }}/${GitHubName}/${{ secrets.REPO }} source

      - name: Setup repo
        run: |
          cd source || exit 1
          sudo cp extract pextract /usr/local/bin ; sudo chmod +x aria.sh /usr/local/bin/extract /usr/local/bin/pextract
          sudo pip3 install -U -r requirements.txt

      - name: Run bot
        continue-on-error: true
        timeout-minutes: 340
        run: |
          sudo chmod -R 777 source ; cd source ; sudo bash go

      - name: Loop Workflow
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          git commit --allow-empty -m "Workflow : Loop"
          git push -f
