name: MirrorBot Environment

on:
  push:
  workflow_dispatch:
   
env:
  GitHubMail: ${{ secrets.GHMAIL }}
  GitHubName: ${{ secrets.GHUSER }}

jobs:
  debug:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store

      - name: Clone Mirror Repo
        run: |
          git clone ${{ secrets.REPO }}mirleech source

      - name: Compile Docker
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot

      - name: Run bot
        continue-on-error: true
        timeout-minutes: 340
        run: |
          docker run --privileged --rm -i mirror-bot
